version: '3.3'
services:
  orai_snapshot:
    container_name: orai_snapshot
    image: orai/orai:snapshot
    working_dir: /snapshot
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/snapshot
