version: '3.3'
services:
  orai:
    container_name: orai_node
    image: orai/orai:0.40.1-alpine
    working_dir: /workspace
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
      - 9091:9090
    cap_add:
      - SYS_PTRACE
    env_file: 
      - orai.env
    command: bash -c 'oraivisor start'
    volumes:
      - ./:/workspace

volumes:
  oraivisor:
